import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Prisma } from "@prisma/client";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

/**
 * Prescription locker (Batch 3). Real Postgres, R2 in STUB mode (bytes land
 * under backend/api/.storage/private). Covers the locker list + unattached
 * filter, the standalone upload (happy path, spoofed content, foreign patient),
 * presigned-file ownership, the "immutable once attached" rule on PATCH/DELETE,
 * and the attach flow including double-attach and non-Rx orders.
 */

// Env must be set BEFORE the app is imported (config/logger parse eagerly).
process.env.NODE_ENV = "test";
process.env.DATABASE_URL ??= "postgresql://postgres@localhost:5433/medrush_c3_test";
delete process.env.FIREBASE_PROJECT_ID;
delete process.env.R2_ACCOUNT_ID; // R2 stub mode → local filesystem

const { buildApp } = await import("../src/app");
const { disconnectPrisma, getPrisma } = await import("../src/core/db");
const { bustFlagCache } = await import("../src/core/flags");
const { bustStoreConfigCache } = await import("../src/core/storeInfo");
const { clearAuthCaches } = await import("../src/plugins/auth");
const { setupTestDb } = await import("./helpers/db");
const { appSettings, storeConfig, user } = await import("./helpers/factories");
const { authHeaders } = await import("./helpers/auth");

type App = Awaited<ReturnType<typeof buildApp>>;

const prisma = getPrisma();
let app: App;

/** A real, sharp-decodable 1×1 transparent PNG (generated by sharp itself). */
const { default: sharp } = await import("sharp");
const REAL_PNG = await sharp({
  create: { width: 1, height: 1, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } },
})
  .png()
  .toBuffer();

/** backend/api/.storage/private — the R2 stub root (resolved from this test file). */
const STORAGE_ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..", ".storage", "private");

interface UploadFile {
  buffer: Buffer;
  filename: string;
  contentType: string;
}

function multipartBody(file: UploadFile | null, fields: Record<string, string> = {}) {
  const boundary = `----medrushTest${randomUUID().replace(/-/g, "")}`;
  const chunks: Buffer[] = [];
  for (const [name, value] of Object.entries(fields)) {
    chunks.push(
      Buffer.from(
        `--${boundary}\r\nContent-Disposition: form-data; name="${name}"\r\n\r\n${value}\r\n`,
      ),
    );
  }
  if (file) {
    chunks.push(
      Buffer.from(
        `--${boundary}\r\n` +
          `Content-Disposition: form-data; name="file"; filename="${file.filename}"\r\n` +
          `Content-Type: ${file.contentType}\r\n\r\n`,
      ),
    );
    chunks.push(file.buffer, Buffer.from("\r\n"));
  }
  chunks.push(Buffer.from(`--${boundary}--\r\n`));
  return { boundary, body: Buffer.concat(chunks) };
}

function uploadLocker(
  headers: Record<string, string>,
  file: UploadFile | null,
  fields: Record<string, string> = {},
) {
  const { boundary, body } = multipartBody(file, fields);
  return app.inject({
    method: "POST",
    url: "/v1/prescriptions",
    headers: { ...headers, "content-type": `multipart/form-data; boundary=${boundary}` },
    payload: body,
  });
}

let seq = 0;

async function makeRxOrder(
  userId: string,
  overrides: Partial<Prisma.OrderUncheckedCreateInput> = {},
) {
  seq += 1;
  return prisma.order.create({
    data: {
      orderNo: `MR-LOCKER-${seq}`,
      userId,
      status: "RX_REVIEW",
      paymentMethod: "COD",
      paymentStatus: "COD_DUE",
      addressSnapshot: {
        name: "Test",
        phone: "+919000000000",
        line1: "1 Test Rd",
        pincode: "560001",
        lat: 12.97,
        lng: 77.59,
      } as Prisma.InputJsonValue,
      distanceM: 100,
      itemsPaise: 10000,
      deliveryPaise: 2000,
      discountPaise: 0,
      totalPaise: 12000,
      requiresRx: true,
      rxStatus: "PENDING",
      ...overrides,
    },
  });
}

async function seedRx(
  userId: string,
  overrides: Partial<Prisma.PrescriptionUncheckedCreateInput> = {},
) {
  return prisma.prescription.create({
    data: {
      userId,
      fileKey: `rx/locker/${userId}/${randomUUID().replace(/-/g, "")}.png`,
      mimeType: "image/png",
      status: "PENDING",
      ...overrides,
    },
  });
}

async function makePatient(userId: string, name = "Asha") {
  return prisma.patient.create({ data: { userId, name, relation: "PARENT" } });
}

beforeAll(async () => {
  app = await buildApp();
  await app.ready();
});

afterAll(async () => {
  await app.close();
  await disconnectPrisma();
});

beforeEach(async () => {
  await setupTestDb();
  clearAuthCaches();
  bustStoreConfigCache();
  bustFlagCache();
  await storeConfig();
  await appSettings();
});

describe("GET /v1/prescriptions", () => {
  it("lists only the caller's prescriptions, newest first, with orderNo when attached", async () => {
    const owner = await user("CUSTOMER");
    const other = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id);
    const patient = await makePatient(owner.id, "Ravi");

    await seedRx(owner.id, {
      label: "Old",
      createdAt: new Date("2026-07-01T00:00:00.000Z"),
      orderId: order.id,
    });
    await seedRx(owner.id, {
      label: "New",
      createdAt: new Date("2026-07-10T00:00:00.000Z"),
      patientId: patient.id,
      doctorName: "Dr Rao",
    });
    await seedRx(other.id, { label: "Someone else's" });

    const res = await app.inject({
      method: "GET",
      url: "/v1/prescriptions",
      headers: authHeaders(owner),
    });
    expect(res.statusCode, res.body).toBe(200);

    const items = res.json().data;
    expect(items).toHaveLength(2);
    expect(items[0].label).toBe("New");
    expect(items[0].orderId).toBeNull();
    expect(items[0].orderNo).toBeNull();
    expect(items[0].patientId).toBe(patient.id);
    expect(items[0].patientName).toBe("Ravi");
    expect(items[0].doctorName).toBe("Dr Rao");
    expect(items[1].label).toBe("Old");
    expect(items[1].orderId).toBe(order.id);
    expect(items[1].orderNo).toBe(order.orderNo);
    expect(res.json().meta.nextCursor).toBeNull();
  });

  it("?unattached=true returns only prescriptions with no order", async () => {
    const owner = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id);
    await seedRx(owner.id, { label: "Attached", orderId: order.id });
    const free = await seedRx(owner.id, { label: "Free" });

    const res = await app.inject({
      method: "GET",
      url: "/v1/prescriptions?unattached=true",
      headers: authHeaders(owner),
    });
    expect(res.statusCode, res.body).toBe(200);

    const items = res.json().data;
    expect(items).toHaveLength(1);
    expect(items[0].id).toBe(free.id);
  });

  it("paginates with a cursor", async () => {
    const owner = await user("CUSTOMER");
    await seedRx(owner.id, { label: "A", createdAt: new Date("2026-07-01T00:00:00.000Z") });
    const newer = await seedRx(owner.id, {
      label: "B",
      createdAt: new Date("2026-07-02T00:00:00.000Z"),
    });

    const first = await app.inject({
      method: "GET",
      url: "/v1/prescriptions?limit=1",
      headers: authHeaders(owner),
    });
    expect(first.statusCode, first.body).toBe(200);
    expect(first.json().data).toHaveLength(1);
    expect(first.json().data[0].id).toBe(newer.id);
    expect(first.json().meta.nextCursor).toBe(newer.id);

    const second = await app.inject({
      method: "GET",
      url: `/v1/prescriptions?limit=1&cursor=${newer.id}`,
      headers: authHeaders(owner),
    });
    expect(second.json().data).toHaveLength(1);
    expect(second.json().data[0].label).toBe("A");
    expect(second.json().meta.nextCursor).toBeNull();
  });

  it("rejects an unauthenticated caller with 401", async () => {
    const res = await app.inject({ method: "GET", url: "/v1/prescriptions" });
    expect(res.statusCode).toBe(401);
  });
});

describe("POST /v1/prescriptions", () => {
  it("stores a standalone PNG under rx/locker/<userId>/ and records it PENDING", async () => {
    const customer = await user("CUSTOMER");
    const patient = await makePatient(customer.id, "Meera");

    const res = await uploadLocker(
      authHeaders(customer),
      { buffer: REAL_PNG, filename: "rx.png", contentType: "image/png" },
      { label: "Dr Rao — Aug", doctorName: "Dr Rao", patientId: patient.id },
    );
    expect(res.statusCode, res.body).toBe(201);

    const rx = res.json().data;
    expect(rx.status).toBe("PENDING");
    expect(rx.mimeType).toBe("image/png");
    expect(rx.orderId).toBeNull();
    expect(rx.orderNo).toBeNull();
    expect(rx.label).toBe("Dr Rao — Aug");
    expect(rx.doctorName).toBe("Dr Rao");
    expect(rx.patientId).toBe(patient.id);
    expect(rx.patientName).toBe("Meera");
    expect(rx.reviewedAt).toBeNull();

    const row = await prisma.prescription.findUnique({ where: { id: rx.id } });
    expect(row?.userId).toBe(customer.id);
    expect(row?.orderId).toBeNull();
    expect(row?.fileKey).toMatch(new RegExp(`^rx/locker/${customer.id}/[a-f0-9]+\\.png$`));

    const stored = await readFile(join(STORAGE_ROOT, row!.fileKey));
    expect(stored.length).toBeGreaterThan(0);
    expect(stored.subarray(0, 4).toString("hex")).toBe("89504e47");
  });

  it("accepts an upload with no optional fields", async () => {
    const customer = await user("CUSTOMER");

    const res = await uploadLocker(authHeaders(customer), {
      buffer: REAL_PNG,
      filename: "rx.png",
      contentType: "image/png",
    });
    expect(res.statusCode, res.body).toBe(201);
    expect(res.json().data.label).toBeNull();
    expect(res.json().data.patientId).toBeNull();
    expect(res.json().data.patientName).toBeNull();
  });

  it("rejects spoofed content (png MIME, non-image bytes) with 422 and stores nothing", async () => {
    const customer = await user("CUSTOMER");

    const res = await uploadLocker(authHeaders(customer), {
      buffer: Buffer.from("this is definitely not a real png"),
      filename: "fake.png",
      contentType: "image/png",
    });
    expect(res.statusCode, res.body).toBe(422);
    expect(res.json().error.code).toBe("VALIDATION_ERROR");
    expect(await prisma.prescription.count()).toBe(0);
  });

  it("rejects a disallowed MIME type with 422", async () => {
    const customer = await user("CUSTOMER");

    const res = await uploadLocker(authHeaders(customer), {
      buffer: REAL_PNG,
      filename: "rx.gif",
      contentType: "image/gif",
    });
    expect(res.statusCode).toBe(422);
    expect(res.json().error.code).toBe("VALIDATION_ERROR");
    expect(await prisma.prescription.count()).toBe(0);
  });

  it("rejects an oversized upload with 422", async () => {
    const customer = await user("CUSTOMER");

    const res = await uploadLocker(authHeaders(customer), {
      buffer: Buffer.alloc(6 * 1024 * 1024, 0x89), // 6MB > 5MB ceiling
      filename: "big.png",
      contentType: "image/png",
    });
    expect(res.statusCode).toBe(422);
    expect(res.json().error.code).toBe("VALIDATION_ERROR");
    expect(await prisma.prescription.count()).toBe(0);
  });

  it("rejects a request with no file part with 422", async () => {
    const customer = await user("CUSTOMER");

    const res = await uploadLocker(authHeaders(customer), null, { label: "No file" });
    expect(res.statusCode).toBe(422);
    expect(res.json().error.code).toBe("VALIDATION_ERROR");
    expect(await prisma.prescription.count()).toBe(0);
  });

  it("rejects an over-long label with 422 before touching storage", async () => {
    const customer = await user("CUSTOMER");

    const res = await uploadLocker(
      authHeaders(customer),
      { buffer: REAL_PNG, filename: "rx.png", contentType: "image/png" },
      { label: "x".repeat(61) },
    );
    expect(res.statusCode).toBe(422);
    expect(res.json().error.code).toBe("VALIDATION_ERROR");
    expect(await prisma.prescription.count()).toBe(0);
  });

  it("404s on another user's patientId and stores nothing", async () => {
    const customer = await user("CUSTOMER");
    const other = await user("CUSTOMER");
    const foreignPatient = await makePatient(other.id);

    const res = await uploadLocker(
      authHeaders(customer),
      { buffer: REAL_PNG, filename: "rx.png", contentType: "image/png" },
      { patientId: foreignPatient.id },
    );
    expect(res.statusCode, res.body).toBe(404);
    expect(await prisma.prescription.count()).toBe(0);
  });
});

describe("GET /v1/prescriptions/:id/file", () => {
  it("returns a short-lived presigned URL to the owner", async () => {
    const owner = await user("CUSTOMER");
    const rx = await seedRx(owner.id);

    const res = await app.inject({
      method: "GET",
      url: `/v1/prescriptions/${rx.id}/file`,
      headers: authHeaders(owner),
    });
    expect(res.statusCode, res.body).toBe(200);
    expect(res.json().data.url).toContain(rx.fileKey);
    expect(res.json().data.expiresInSec).toBe(300);
    expect(res.headers["cache-control"]).toBe("no-store");
  });

  it("404s for another user (ids cannot be probed)", async () => {
    const owner = await user("CUSTOMER");
    const other = await user("CUSTOMER");
    const rx = await seedRx(owner.id);

    const res = await app.inject({
      method: "GET",
      url: `/v1/prescriptions/${rx.id}/file`,
      headers: authHeaders(other),
    });
    expect(res.statusCode).toBe(404);
    expect(res.json().error.code).toBe("NOT_FOUND");
  });
});

describe("PATCH /v1/prescriptions/:id", () => {
  it("updates label, doctorName and patientId on an unattached prescription", async () => {
    const owner = await user("CUSTOMER");
    const patient = await makePatient(owner.id, "Nita");
    const rx = await seedRx(owner.id, { label: "Old" });

    const res = await app.inject({
      method: "PATCH",
      url: `/v1/prescriptions/${rx.id}`,
      headers: authHeaders(owner),
      payload: { label: "Aug refill", doctorName: "Dr Iyer", patientId: patient.id },
    });
    expect(res.statusCode, res.body).toBe(200);
    expect(res.json().data.label).toBe("Aug refill");
    expect(res.json().data.doctorName).toBe("Dr Iyer");
    expect(res.json().data.patientName).toBe("Nita");
  });

  it("clears the patient link when patientId is null", async () => {
    const owner = await user("CUSTOMER");
    const patient = await makePatient(owner.id);
    const rx = await seedRx(owner.id, { patientId: patient.id });

    const res = await app.inject({
      method: "PATCH",
      url: `/v1/prescriptions/${rx.id}`,
      headers: authHeaders(owner),
      payload: { patientId: null },
    });
    expect(res.statusCode, res.body).toBe(200);
    expect(res.json().data.patientId).toBeNull();
    expect(res.json().data.patientName).toBeNull();
  });

  it("404s on another user's patientId", async () => {
    const owner = await user("CUSTOMER");
    const other = await user("CUSTOMER");
    const foreignPatient = await makePatient(other.id);
    const rx = await seedRx(owner.id);

    const res = await app.inject({
      method: "PATCH",
      url: `/v1/prescriptions/${rx.id}`,
      headers: authHeaders(owner),
      payload: { patientId: foreignPatient.id },
    });
    expect(res.statusCode).toBe(404);
    expect((await prisma.prescription.findUnique({ where: { id: rx.id } }))?.patientId).toBeNull();
  });

  it("409s once the prescription is attached to an order", async () => {
    const owner = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id);
    const rx = await seedRx(owner.id, { orderId: order.id, label: "Locked" });

    const res = await app.inject({
      method: "PATCH",
      url: `/v1/prescriptions/${rx.id}`,
      headers: authHeaders(owner),
      payload: { label: "Renamed" },
    });
    expect(res.statusCode, res.body).toBe(409);
    expect(res.json().error.code).toBe("CONFLICT");
    expect((await prisma.prescription.findUnique({ where: { id: rx.id } }))?.label).toBe("Locked");
  });

  it("404s and does not mutate another user's prescription", async () => {
    const owner = await user("CUSTOMER");
    const other = await user("CUSTOMER");
    const rx = await seedRx(owner.id, { label: "Mine" });

    const res = await app.inject({
      method: "PATCH",
      url: `/v1/prescriptions/${rx.id}`,
      headers: authHeaders(other),
      payload: { label: "Hijacked" },
    });
    expect(res.statusCode).toBe(404);
    expect((await prisma.prescription.findUnique({ where: { id: rx.id } }))?.label).toBe("Mine");
  });

  it("400s on an empty label", async () => {
    const owner = await user("CUSTOMER");
    const rx = await seedRx(owner.id);

    const res = await app.inject({
      method: "PATCH",
      url: `/v1/prescriptions/${rx.id}`,
      headers: authHeaders(owner),
      payload: { label: "" },
    });
    expect(res.statusCode).toBe(400);
    expect(res.json().error.code).toBe("VALIDATION_ERROR");
  });
});

describe("DELETE /v1/prescriptions/:id", () => {
  it("removes an unattached prescription", async () => {
    const owner = await user("CUSTOMER");
    const rx = await seedRx(owner.id);

    const res = await app.inject({
      method: "DELETE",
      url: `/v1/prescriptions/${rx.id}`,
      headers: authHeaders(owner),
    });
    expect(res.statusCode, res.body).toBe(200);
    expect(res.json().data.ok).toBe(true);
    expect(await prisma.prescription.count()).toBe(0);
  });

  it("409s once attached to an order", async () => {
    const owner = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id);
    const rx = await seedRx(owner.id, { orderId: order.id });

    const res = await app.inject({
      method: "DELETE",
      url: `/v1/prescriptions/${rx.id}`,
      headers: authHeaders(owner),
    });
    expect(res.statusCode, res.body).toBe(409);
    expect(res.json().error.code).toBe("CONFLICT");
    expect(await prisma.prescription.count()).toBe(1);
  });

  it("404s for another user and leaves the row alone", async () => {
    const owner = await user("CUSTOMER");
    const other = await user("CUSTOMER");
    const rx = await seedRx(owner.id);

    const res = await app.inject({
      method: "DELETE",
      url: `/v1/prescriptions/${rx.id}`,
      headers: authHeaders(other),
    });
    expect(res.statusCode).toBe(404);
    expect(await prisma.prescription.findUnique({ where: { id: rx.id } })).not.toBeNull();
  });
});

describe("POST /v1/orders/:id/prescriptions/attach", () => {
  it("records a PENDING dispensing and leaves the document re-usable", async () => {
    const owner = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id);
    const rx = await seedRx(owner.id, { label: "Chronic" });

    const res = await app.inject({
      method: "POST",
      url: `/v1/orders/${order.id}/prescriptions/attach`,
      headers: authHeaders(owner),
      payload: { prescriptionId: rx.id },
    });
    expect(res.statusCode, res.body).toBe(200);

    const dispensing = await prisma.orderPrescription.findFirstOrThrow({
      where: { orderId: order.id, prescriptionId: rx.id },
    });
    expect(dispensing.status).toBe("PENDING");
    expect(dispensing.reviewedAt).toBeNull();
    // Only the pharmacist review flips the order's rxStatus.
    expect((await prisma.order.findUnique({ where: { id: order.id } }))?.rxStatus).toBe("PENDING");
  });

  it("re-uses one prescription across several orders, each needing its own review", async () => {
    // The whole point of the locker: a chronic patient uploads once. Each order
    // still gets its own dispensing row for the pharmacist to adjudicate.
    const owner = await user("CUSTOMER");
    const first = await makeRxOrder(owner.id);
    const second = await makeRxOrder(owner.id);
    const rx = await seedRx(owner.id);

    for (const order of [first, second]) {
      const res = await app.inject({
        method: "POST",
        url: `/v1/orders/${order.id}/prescriptions/attach`,
        headers: authHeaders(owner),
        payload: { prescriptionId: rx.id },
      });
      expect(res.statusCode, res.body).toBe(200);
    }

    const dispensings = await prisma.orderPrescription.findMany({
      where: { prescriptionId: rx.id },
    });
    expect(dispensings).toHaveLength(2);
    expect(dispensings.every((d) => d.status === "PENDING")).toBe(true);
  });

  it("does not let a previous APPROVAL carry over to a new order", async () => {
    // The compliance property: a pharmacist authorises a SPECIFIC dispensing.
    // Re-using an approved prescription must not silently authorise the next
    // order — it starts PENDING and goes back through review.
    const owner = await user("CUSTOMER");
    const approvedOrder = await makeRxOrder(owner.id);
    const rx = await seedRx(owner.id, { status: "APPROVED" });
    await prisma.orderPrescription.create({
      data: {
        orderId: approvedOrder.id,
        prescriptionId: rx.id,
        status: "APPROVED",
        reviewedAt: new Date(),
      },
    });

    const nextOrder = await makeRxOrder(owner.id);
    const res = await app.inject({
      method: "POST",
      url: `/v1/orders/${nextOrder.id}/prescriptions/attach`,
      headers: authHeaders(owner),
      payload: { prescriptionId: rx.id },
    });
    expect(res.statusCode, res.body).toBe(200);

    const fresh = await prisma.orderPrescription.findFirstOrThrow({
      where: { orderId: nextOrder.id, prescriptionId: rx.id },
    });
    expect(fresh.status).toBe("PENDING");
    expect(fresh.reviewedAt).toBeNull();
    expect((await prisma.order.findUnique({ where: { id: nextOrder.id } }))?.rxStatus).toBe(
      "PENDING",
    );
  });

  it("409s when the same prescription is attached to the same order twice", async () => {
    const owner = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id);
    const rx = await seedRx(owner.id);
    const attach = () =>
      app.inject({
        method: "POST",
        url: `/v1/orders/${order.id}/prescriptions/attach`,
        headers: authHeaders(owner),
        payload: { prescriptionId: rx.id },
      });

    expect((await attach()).statusCode).toBe(200);
    const again = await attach();
    expect(again.statusCode, again.body).toBe(409);
    expect(again.json().error.code).toBe("CONFLICT");
    expect(await prisma.orderPrescription.count({ where: { prescriptionId: rx.id } })).toBe(1);
  });

  it("422s when the order does not require a prescription", async () => {
    const owner = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id, {
      requiresRx: false,
      rxStatus: "NA",
      status: "PLACED",
    });
    const rx = await seedRx(owner.id);

    const res = await app.inject({
      method: "POST",
      url: `/v1/orders/${order.id}/prescriptions/attach`,
      headers: authHeaders(owner),
      payload: { prescriptionId: rx.id },
    });
    expect(res.statusCode, res.body).toBe(422);
    expect(res.json().error.code).toBe("VALIDATION_ERROR");
    expect(await prisma.orderPrescription.count({ where: { prescriptionId: rx.id } })).toBe(0);
  });

  it("409s when the order is terminal", async () => {
    const owner = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id, { status: "CANCELLED" });
    const rx = await seedRx(owner.id);

    const res = await app.inject({
      method: "POST",
      url: `/v1/orders/${order.id}/prescriptions/attach`,
      headers: authHeaders(owner),
      payload: { prescriptionId: rx.id },
    });
    expect(res.statusCode, res.body).toBe(409);
    expect(res.json().error.code).toBe("CONFLICT");
  });

  it("409s when the order is no longer awaiting a prescription", async () => {
    const owner = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id, { rxStatus: "APPROVED" });
    const rx = await seedRx(owner.id);

    const res = await app.inject({
      method: "POST",
      url: `/v1/orders/${order.id}/prescriptions/attach`,
      headers: authHeaders(owner),
      payload: { prescriptionId: rx.id },
    });
    expect(res.statusCode, res.body).toBe(409);
    expect(res.json().error.code).toBe("CONFLICT");
  });

  it("404s on another user's order", async () => {
    const owner = await user("CUSTOMER");
    const other = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id);
    const rx = await seedRx(other.id);

    const res = await app.inject({
      method: "POST",
      url: `/v1/orders/${order.id}/prescriptions/attach`,
      headers: authHeaders(other),
      payload: { prescriptionId: rx.id },
    });
    expect(res.statusCode).toBe(404);
    expect((await prisma.prescription.findUnique({ where: { id: rx.id } }))?.orderId).toBeNull();
  });

  it("404s on another user's prescription", async () => {
    const owner = await user("CUSTOMER");
    const other = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id);
    const foreignRx = await seedRx(other.id);

    const res = await app.inject({
      method: "POST",
      url: `/v1/orders/${order.id}/prescriptions/attach`,
      headers: authHeaders(owner),
      payload: { prescriptionId: foreignRx.id },
    });
    expect(res.statusCode).toBe(404);
    expect(res.json().error.code).toBe("NOT_FOUND");
    expect((await prisma.prescription.findUnique({ where: { id: foreignRx.id } }))?.orderId).toBeNull();
  });

  it("400s when prescriptionId is missing", async () => {
    const owner = await user("CUSTOMER");
    const order = await makeRxOrder(owner.id);

    const res = await app.inject({
      method: "POST",
      url: `/v1/orders/${order.id}/prescriptions/attach`,
      headers: authHeaders(owner),
      payload: {},
    });
    expect(res.statusCode).toBe(400);
    expect(res.json().error.code).toBe("VALIDATION_ERROR");
  });
});

describe("POST /v1/orders/:id/prescriptions (unchanged)", () => {
  it("still uploads against an order and sets userId + orderId", async () => {
    const customer = await user("CUSTOMER");
    const order = await makeRxOrder(customer.id);
    const { boundary, body } = multipartBody({
      buffer: REAL_PNG,
      filename: "rx.png",
      contentType: "image/png",
    });

    const res = await app.inject({
      method: "POST",
      url: `/v1/orders/${order.id}/prescriptions`,
      headers: {
        ...authHeaders(customer),
        "content-type": `multipart/form-data; boundary=${boundary}`,
      },
      payload: body,
    });
    expect(res.statusCode, res.body).toBe(201);

    const row = await prisma.prescription.findUnique({ where: { id: res.json().data.id } });
    expect(row?.userId).toBe(customer.id);
    expect(row?.orderId).toBe(order.id);
    expect(row?.fileKey).toMatch(new RegExp(`^rx/${order.id}/[a-f0-9]+\\.png$`));
  });
});
